on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on push events to the main branch
  push:
    branches:
      - main

name: 'Business Greetings'
description: 'Offers professional greetings and timestamps them'
inputs:
  name:
    description: 'Name of the person or team to greet'
    required: true
    default: 'Udacity Learner'
outputs:
  timestamp:
    description: 'Time of greeting'
runs:
  using: 'composite'
  main: 'main.py'
